### ISSUE TITLE
please help what is an irc password?

### ISSUE THREAD

**Issue by SpeedyWithS** [Meowhal/osu-ahr#158] opened 2022-12-23 21:39 UTC
The only thing I can find on the IRC old osu website that is linked is "server password" but when I try and put that in it doesn't work. When I run `npm run start` it just tells me:

> osu-ahr@1.6.1 start

> node dist/cli/index.js

> 
> Loading log4js configuration from ./config/log_cli.json
> 
> [00:52:42.769][INFO] pre - Starting up...
> 
> [00:52:42.772][ERROR] pre - You must enter your account ID and IRC password in the config file.
> 
> [00:52:42.772][ERROR] pre - You can get your IRC password in 'https://osu.ppy.sh/p/irc'
> 
> [00:52:42.772][ERROR] pre - Copy config/default.json to config/local.json, and then enter your account ID and IRC password

I tried everything and googled for around 2 hours but to no avail. Please help and if you can, explain to me in detail what an irc password and where to find it.

**Comment by matte-ek** [comment] 2022-12-23 23:46
The server password should be the correct password. Have you made sure to copy the `config/default.json` to `config/local.json`? Then only change the `config/local.json` file with the correct details.

**Comment by SpeedyWithS** [comment] 2022-12-23 23:50
> The server password should be the correct password. Have you made sure to copy the `config/default.json` to `config/local.json`? Then only change the `config/local.json` file with the correct details.

I just renamed the default.json to local.json. Isn't that what I was supposed to do? Maybe I interpreted it wrong

**Comment by matte-ek** [comment] 2022-12-23 23:55
Shouldn't be an issue, but you could try just copying it instead, leaving the `default.json` untouched. The error itself seems to just indicate that it can't read the config credentials.

**Comment by SpeedyWithS** [comment] 2022-12-24 00:18
> Shouldn't be an issue, but you could try just copying it instead, leaving the `default.json` untouched. The error itself seems to just indicate that it can't read the config credentials.

Tried that as well. Or rather, I renamed, went into the original zip from which I extracted the folder, thus creating a copy, and got the default.json from there to then put it in with the renamed file. No difference.

**Comment by xayanide** [comment] 2022-12-24 13:54
Can you please show us your directory tree inside your osu-ahr folder?

**Comment by SpeedyWithS** [comment] 2022-12-25 01:36
> Can you please show us your directory tree inside your osu-ahr folder?

I'm not entirely sure what you mean by directory tree but I tried my best to deliver anyways :) Sorry if it's not what you asked for.
![image](https://user-images.githubusercontent.com/121319287/209454676-fc17898c-8752-4ed2-8c7c-693067aa0dfd.png)
![image](https://user-images.githubusercontent.com/121319287/209454683-194518ea-14ed-45b6-9643-b26f830672a3.png)
![image](https://user-images.githubusercontent.com/121319287/209454689-da168858-a70d-4f7c-9eaf-83ed06ab349b.png)
![image](https://user-images.githubusercontent.com/121319287/209454692-d7502b6d-1dfb-47b7-a829-677e3550b00a.png)
![image](https://user-images.githubusercontent.com/121319287/209454699-1483ed1a-338b-44b6-a2f8-e10e2e12d9f4.png)

I also got this incase it helps :)
![ima5465ge43](https://user-images.githubusercontent.com/121319287/209454724-61810329-4ce6-42b8-9e8f-7e95e43aac58.png)

**Comment by xayanide** [comment] 2022-12-25 04:23
Odd, I am unable to reproduce this.
By the way in the `local.json` file at the value for `irc.nick`, instead of numbers `29365787`, you put the username of your osu! account, not the id.

a.) Try opening up a terminal inside the `osu-ahr-master` folder and run `npm run start` from there if you haven't already.

b.) Try reviewing the steps you've done using https://www.youtube.com/watch?v=8kYbBWgMfIQ, in the video they are using an older version of osu-ahr but the steps should still be similar.

**Comment by SpeedyWithS** [comment] 2022-12-28 19:18
The video worked! Thank you so much man I really appreciate still helping people after all these years!

**Comment by xayanide** [comment] 2022-12-29 18:51
Which specific step caused and solved your issue for reference purposes? Please don't forget to close this issue as completed.

**Comment by SpeedyWithS** [comment] 2022-12-30 02:45
Doing the excact same things as I did before, but downloading the dev branch instead of master, naming the default.json to development.json instead of local.json, and right clicking inside to folder and click "open git bash here" instead of using the cd command to get into it.

Also sorry for not changing to complete. This is my first ever time using github :D

**Comment by SpeedyWithS** [comment] 2022-12-30 02:47
Case closed lol

**Closed as completed** 2022-12-30 02:46 UTC
